apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp
  namespace: sisonke   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      imagePullSecrets:       
        - name: ghcr-secret    
      containers:
      - name: taskapp
        image: ghcr.io/bhts-quadops/taskapp:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: taskapp-secret
