apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-core-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: argocd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-core-server
            port:
              number: 80